# Generated by Django 4.2.6 on 2023-11-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0004_gamepromotion_oldprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='isOnPromotion',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
