# Generated by Django 4.2.6 on 2023-12-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0005_game_isonpromotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepromotion',
            name='oldPrice',
            field=models.FloatField(default=0),
        ),
    ]
