# Generated by Django 4.2.6 on 2023-12-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0007_newrelease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='isOnPromotion',
            field=models.BooleanField(default=False),
        ),
    ]
