# Generated by Django 4.2.6 on 2023-11-25 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0003_preordergame_gamepromotion'),
        ('user', '0002_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WishListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userwishlist')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.game')),
            ],
        ),
        migrations.AddField(
            model_name='userwishlist',
            name='game',
            field=models.ManyToManyField(through='user.WishListItem', to='browse.game'),
        ),
        migrations.AddField(
            model_name='userwishlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
