# Generated by Django 4.2.6 on 2023-11-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='edition',
            field=models.CharField(choices=[('physical', 'physical'), ('digital', 'digital')], default='digital', max_length=8),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='platform',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
