# Generated by Django 4.2.6 on 2023-11-28 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0003_preordergame_gamepromotion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_cartitem_edition_cartitem_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.FloatField()),
                ('orderDate', models.DateField()),
                ('isShipped', models.BooleanField()),
                ('isReceived', models.BooleanField()),
                ('orderItems', models.ManyToManyField(to='browse.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=200)),
                ('edition', models.CharField(max_length=8)),
                ('platform', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
