# Generated by Django 4.2.6 on 2023-11-10 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('publisher', models.CharField(max_length=100)),
                ('developer', models.CharField(max_length=100)),
                ('releaseDate', models.DateField()),
                ('image', models.ImageField(upload_to='images/game')),
            ],
        ),
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platformName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GameplayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameplayImage', models.ImageField(upload_to='images/game/gameplayImages/')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gameplay_images', to='browse.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='gameCategories',
            field=models.ManyToManyField(to='browse.gamecategory'),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(to='browse.platform'),
        ),
    ]
