# Generated by Django 4.2.6 on 2023-11-25 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_gamecapabilities_game_physicalcopyquantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrderGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('publisher', models.CharField(max_length=100)),
                ('developer', models.CharField(max_length=100)),
                ('releaseDate', models.DateField()),
                ('image', models.ImageField(upload_to='images/game')),
                ('platforms', models.ManyToManyField(to='browse.platform')),
            ],
        ),
        migrations.CreateModel(
            name='GamePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newPrice', models.FloatField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.game')),
            ],
        ),
    ]
