# Generated by Django 4.2.6 on 2023-11-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0003_preordergame_gamepromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepromotion',
            name='oldPrice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
