# Generated by Django 4.2.6 on 2023-11-25 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userwishlist_wishlistitem_userwishlist_game_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='cart',
            new_name='wishList',
        ),
    ]
