# Generated by Django 4.2.6 on 2023-12-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='approved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
